### PR TITLE
Upgrading core dependencies and adding support for gRPC based EventStore client

### PR DESCRIPTION
**Pull request by kristian-elder**
This change is [Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)

### CODE REVIEW

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 18 of 41 files at r1, 13 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 31 of 44 files reviewed, 6 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-core/src/test/java/org/elder/sourcerer/subscription/EventSubscriptionManagerTest.java` line 106 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jcbHy4uS0kUW9s-ce:-N0jcbHy4uS0kUW9s-cf:b-jrj0) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-core/src/test/java/org/elder/sourcerer/subscription/EventSubscriptionManagerTest.java#L106)):*
> ```Java
>                             lastProducedValue = e.getEvent().getEvent();
>                         })
>                         .publishOn(Schedulers.parallel())
> ```

I think you will have t explain this to me :sweat_smile: 
___
*[`sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java` line 276 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jd-TxDMXQZMm8gHpz:-N0jd-Ty8ULQr9G-gjIb:bcfcmvj) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java#L276)):*
> ```Java
>                 streamId, streamPrefix, fromVersion);
> 
>         return Flux.create((FluxSink<EventSubscriptionUpdate<T>> emitter) -> {
> ```

A sink sounds like the opposite of an emitter..?



_Code quote:_
```Java
FluxSink<EventSubscriptionUpdate<T>> emitter
```
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 60 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jdhYU8Lyqd9SQS8ND:-N0jdhYV5hwPcRM248Ix:bitagz5) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L60)):*
> ```Java
>  * The EventStore implementation uses Jackson to serialize and deserialize events that are
>  * subclasses of the given event type base class. To instruct Jackson on how to correctly
>  * deserialize events to the correct concrete sub type, please use either the Jaconson annotations,
> ```

Jackson?



_Code quote:_
```Java
Jaconson
```
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 276 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jg5qe9RYovHSkdmfl:-N0jg5qe9RYovHSkdmfm:b3igojg) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L276)):*
> ```Java
>                 ),
>                 ExpectedVersion.any());
>         return readResult == null || readResult.getEvents() != null
> ```

Should this not be `== null`?



_Code quote:_
```Java
readResult.getEvents() != null
```
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 318 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jhCOc5NycptxF4Mn3:-N0jhCOc5NycptxF4Mn4:b-2cab3p) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L318)):*
> ```Java
>                             SubscribeToStreamOptions.get()
>                                     .fromRevision(toStreamRevision(fromVersion))
>                                     .resolveLinkTos()), ExpectedVersion.any());
> ```

Do we also have to specify "any version" for this publisher?
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 440 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jiDpW3do_n3JQxp8r:-N0jiDpW3do_n3JQxp8s:bk21rf4) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L440)):*
> ```Java
>         } catch (InterruptedException ex) {
>             Thread.currentThread().interrupt();
>             throw new RetriableEventReadException("Internal error reading event", ex);
> ```

Not sure, but if it was interrupted, should it really be retriable?



_Code quote:_
```Java
throw new RetriableEventReadException("Internal error reading event", ex);
```

**Review by danieljelder — COMMENTED** [review]
> Reviewed 8 of 41 files at r1, 4 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 43 of 44 files reviewed, 7 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java` line 181 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jkCd--XyLcPW_SGVi:-N0jkCd0BYVf1ZcxrxZi:b8deajc) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java#L181)):*
> ```Java
>                 ArgumentCaptor.forClass(SubscriptionListener.class);
> 
>         verify(eventStore, times(1)).subscribeToStream(
> ```

What in this test checks ensures the reactor doesn't introduce issues due to a blocked callback?

**Review by danieljelder — COMMENTED** [review]
> Reviewed 1 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 7 unresolved discussions (waiting on @kristian-elder)

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 8 unresolved discussions (waiting on @kristian-elder)

___
*[`sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt` line 124 at r8](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1Olm4TEIxJMgrRLm9f:-N1Olm4TEIxJMgrRLm9g:b-ge0jgs) ([raw file](https://github.com/elder-oss/sourcerer/blob/1771ae746f32833e530f96ac047eae3dbc34d4be/sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt#L124)):*
> ```Kotlin
> 
>             // Give the world a moment to catch up
>             Thread.sleep(5000)
> ```

Might run quicker/run more reliably if the subscription updates a latch saying it's consumed the events.



_Code quote:_
```Kotlin
Thread.sleep(5000)
```

**Review by danieljelder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 9 unresolved discussions (waiting on @kristian-elder)

___
*[`sourcerer-core/build.gradle` line 7 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jbEDy9AarPAWgsbmZ:-N0jbEDy9AarPAWgsbm_:b-bwdyd0) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-core/build.gradle#L7)):*
> ```Gradle
>     implementation 'com.google.guava:guava:31.1-jre'
>     implementation platform('io.projectreactor:reactor-bom:2020.0.18')
>     implementation 'io.projectreactor:reactor-core'
> ```

What version are we using now?



_Code quote:_
```Gradle
io.projectreactor:reactor-core
```

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 9 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-core/build.gradle` line 7 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jbEDy9AarPAWgsbmZ:-N1h0aYc4GollcNoimzf:b-yqkk89) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-core/build.gradle#L7)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

What version are we using now?
</blockquote></details>

The latest, now comes from the bom, see line above.

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 9 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-core/src/test/java/org/elder/sourcerer/subscription/EventSubscriptionManagerTest.java` line 106 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jcbHy4uS0kUW9s-ce:-N1h0iqv7Cy8LUseQYjN:bzqpbu) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-core/src/test/java/org/elder/sourcerer/subscription/EventSubscriptionManagerTest.java#L106)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

I think you will have t explain this to me :sweat_smile: 
</blockquote></details>

Happy to :) In short, reactor is synchronus by default, the thread that triggers an event is the thread that runs the subscribers attached to that observable. 

Before we were using the "work queue processor" which was another way to decouple an observable from the subscription whreas now the equivalent is using a Scheduler for this step.

All that being said, I don't know why we needed the async processor here (and its equivalent now) in the first place!
___
*[`sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java` line 276 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jd-TxDMXQZMm8gHpz:-N1h1kfX2ISo6xIro_Yu:b-rfmreo) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java#L276)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

A sink sounds like the opposite of an emitter..?
</blockquote></details>

Happy to rename, though they've used this terminology in examples.

The sink here is what's used to emit event to the subscribers of the flux ultimately. From our end it's a sink that you can publish to, but it's used to implement a Flux which is a source for others..
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 60 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jdhYU8Lyqd9SQS8ND:-N1h2RV98DwxtFiUyw3S:bt2vr0y) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L60)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Jackson?
</blockquote></details>

Fixed!

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 9 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 276 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jg5qe9RYovHSkdmfl:-N1h449T4YikU09usme3:b-7ws2py) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L276)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Should this not be `== null`?
</blockquote></details>

Indeed it should! Have reworked this big.



_Code quote:_
```Java
        return readResult == null || readResult.getEvents() != null
```

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 46 of 48 files reviewed, 9 unresolved discussions (waiting on @danieljelder)

___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 318 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jhCOc5NycptxF4Mn3:-N1h4yPL7Hx-LGo3E1BA:b-7j5zie) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L318)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Do we also have to specify "any version" for this publisher?
</blockquote></details>

This is a big of a hack. The "read" helper uses the exepcted version only in exceptions if we have specific errors indicating a race / failed optimistic concurrency check.
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 440 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jiDpW3do_n3JQxp8r:-N1h4_kN56hjMVVUVEAt:bna99vd) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L440)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Not sure, but if it was interrupted, should it really be retriable?
</blockquote></details>

I don't think we use these in any meaingful way, but I'd interpret the retriable as "is there a chance the data is actually there".

That being said, I've never _really_ understood the interrup machine, this should never ever happen unless we ask for it somewhere (or are shutting down), right?
___
*[`sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java` line 181 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jkCd--XyLcPW_SGVi:-N1h6Qa5223MGvoGwZGQ:bfbay23) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java#L181)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

What in this test checks ensures the reactor doesn't introduce issues due to a blocked callback?
</blockquote></details>

An excellent question that, this was ported from the old code but no long sure what the actual test is...
___
*[`sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt` line 124 at r8](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1Olm4TEIxJMgrRLm9f:-N1h6G341eEY0xGz9-Mv:b-8oda5w) ([raw file](https://github.com/elder-oss/sourcerer/blob/1771ae746f32833e530f96ac047eae3dbc34d4be/sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt#L124)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Might run quicker/run more reliably if the subscription updates a latch saying it's consumed the events.
</blockquote></details>

True, though I'd also want to see that we don't get _too many_ events.,

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 6 unresolved discussions (waiting on @danieljelder and @kristian-elder)

___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 440 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jiDpW3do_n3JQxp8r:-N1h7R4KAMCHGJ-sMDZf:beuoh3e) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L440)):*
<details><summary><i>Previously, kristian-elder wrote…</i></summary><blockquote>

I don't think we use these in any meaingful way, but I'd interpret the retriable as "is there a chance the data is actually there".

That being said, I've never _really_ understood the interrup machine, this should never ever happen unless we ask for it somewhere (or are shutting down), right?
</blockquote></details>

Yeah interrupts should only happen if you explicitly do it, or asking the VM to shut down. Interrupts were very important to handle right according to books back in the day...

I think since you set the flag again it should be fine, it's just that the "retriable" part is confusing :)
___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 284 at r9](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1h6o_o7GqSqBaXbH4S:-N1h6o_o7GqSqBaXbH4T:bbi3fsm) ([raw file](https://github.com/elder-oss/sourcerer/blob/e8275bc801f451d0764a0e36454acd8324e7af76/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L284)):*
> ```Java
>                 ? fromStreamRevision(
>                 readResult.getEvents().get(0).getOriginalEvent().getStreamRevision())
>                 : -1;
> ```

For clarity when reading (and potentially using), it might be useful to extract these magic numbers to constants



_Code quote:_
```Java
-1
```
___
*[`sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java` line 181 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jkCd--XyLcPW_SGVi:-N1h8Kjb6-pdWjdAs2DZ:b-j3tiit) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java#L181)):*
<details><summary><i>Previously, kristian-elder wrote…</i></summary><blockquote>

An excellent question that, this was ported from the old code but no long sure what the actual test is...
</blockquote></details>

Maybe add a comment saying that then, if/when we get back to this in the future it would be good to know it was universally unknown :sweat_smile:

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 37 of 52 files reviewed, 1 unresolved discussion (waiting on @danieljelder)

___
*[`sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java` line 284 at r9](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1h6o_o7GqSqBaXbH4S:-N1hNnTx70s1tUHLQ092:b-896fja) ([raw file](https://github.com/elder-oss/sourcerer/blob/e8275bc801f451d0764a0e36454acd8324e7af76/sourcerer-eventstore-grpc/src/main/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepository.java#L284)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

For clarity when reading (and potentially using), it might be useful to extract these magic numbers to constants
</blockquote></details>

Done!
___
*[`sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java` line 181 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N0jkCd--XyLcPW_SGVi:-N1hNpTADz9IEfmDOxcg:bmfxgaw) ([raw file](https://github.com/elder-oss/sourcerer/blob/66e1ee9c711a8d9a73a575d59b2c6241414c9a98/sourcerer-eventstore-grpc/src/test/java/org/elder/sourcerer/eventstoredb/EventStoreGrpcEventRepositoryTest.java#L181)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Maybe add a comment saying that then, if/when we get back to this in the future it would be good to know it was universally unknown :sweat_smile: 
</blockquote></details>

Done :)

**Review by danieljelder — APPROVED** [review]
> Reviewed 15 of 15 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 1 unresolved discussion (waiting on @kristian-elder)

___
*[`sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt` line 12 at r11](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1hPmB_-OGtBITjG3kj:-N1hPmB_-OGtBITjG3kk:b-misvmj) ([raw file](https://github.com/elder-oss/sourcerer/blob/1184286d07c3ce31a33e085e8857b74788ae0a1c/sourcerer-eventstore-grpc-tests/src/test/kotlin/org/elder/sourcerer/eventstoredb/tests/EventStoreGrpcEventRepositoryIntegrationTest.kt#L12)):*
> ```Kotlin
> import org.elder.sourcerer.eventstoredb.EventStoreGrpcEventRepositoryFactory
> 
> class EventStoreGrpcEventRepositoryIntegrationTest : EventStorEventRepositoryIntegrationTestBase() {
> ```

Nit: `Store`*



_Code quote:_
```Kotlin
Stor
```

**Review by danieljelder — APPROVED** [review]
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 1 unresolved discussion (waiting on @kristian-elder)

**Review by danieljelder — APPROVED** [review]
> Reviewed 2 of 4 files at r13, 1 of 2 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kristian-elder)

**Review by danieljelder — APPROVED** [review]
> Reviewed 27 of 27 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 1 unresolved discussion (waiting on @kristian-elder)

___
*[`sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java` line 130 at r16](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1irh_z-lrtWdzI-SYN:-N1irh_z-lrtWdzI-SYO:b-ovklce) ([raw file](https://github.com/elder-oss/sourcerer/blob/61f7fb0a1430d5a5a7b14e4bc9dce015df6787c4/sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java#L130)):*
> ```Java
>     }
> 
>     // Not part of public interface, but used for inspection / testing
> ```

Does the method look unused in the IDE? It's private



_Code quote:_
```Java
// Not part of public interface, but used for inspection / testing
```

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 62 of 69 files reviewed, 1 unresolved discussion (waiting on @danieljelder)

___
*[`sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java` line 130 at r16](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N1irh_z-lrtWdzI-SYN:-N2LNdDyB4xCfcV-_Ye0:b-8m4tnw) ([raw file](https://github.com/elder-oss/sourcerer/blob/61f7fb0a1430d5a5a7b14e4bc9dce015df6787c4/sourcerer-esjc/src/main/java/org/elder/sourcerer/esjc/EventStoreEsjcEventRepository.java#L130)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Does the method look unused in the IDE? It's private
</blockquote></details>

Your guess is as good as mine! Removed.

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: all files reviewed, 2 unresolved discussions (waiting on @kristian-elder)

___
*[`sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt` line 15 at r17](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N2LXORg0evmm3wszjIs:-N2LXORg0evmm3wszjIt:b3kqx) ([raw file](https://github.com/elder-oss/sourcerer/blob/e59e196edd6b5dd5582781424780cac082258a5f/sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt#L15)):*
> ```Kotlin
>             .addHost(Endpoint("127.0.0.1", 2113))
>             .addHost(Endpoint("127.0.0.1", 2114))
>             // .addHost(Endpoint("127.0.0.1", 2115))
> ```

.



_Code quote:_
```Kotlin
// .addHost(Endpoint("127.0.0.1", 2115))
```
___
*[`sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt` line 17 at r17](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N2LXTCQDR-OVkxAl6hd:-N2LXTCQDR-OVkxAl6he:bne2sme) ([raw file](https://github.com/elder-oss/sourcerer/blob/e59e196edd6b5dd5582781424780cac082258a5f/sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt#L17)):*
> ```Kotlin
>             // .addHost(Endpoint("127.0.0.1", 2115))
>             .defaultCredentials("admin", "changeit")
>             .nodePreference(NodePreference.FOLLOWER)
> ```

Is there a specific reason for specifying follower? If so, it would be good with a comment



_Code quote:_
```Kotlin
.nodePreference(NodePreference.FOLLOWER)
```

**Review by kristian-elder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: 68 of 69 files reviewed, 2 unresolved discussions (waiting on @danieljelder)

___
*[`sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt` line 17 at r17](https://reviewable.io/reviews/elder-oss/sourcerer/30#-N2LXTCQDR-OVkxAl6hd:-N2LkPAE05SAb3w0F594:b-3dghn8) ([raw file](https://github.com/elder-oss/sourcerer/blob/e59e196edd6b5dd5582781424780cac082258a5f/sourcerer-eventstore-grpc-tests/src/integrationTest/kotlin/org/elder/sourcerer/eventstoredb/utils.kt#L17)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Is there a specific reason for specifying follower? If so, it would be good with a comment
</blockquote></details>

As above, fixed

**Review by danieljelder — APPROVED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kristian-elder)

**Pull request merged**
