### PR TITLE
Compressed snapshots

### PR DESCRIPTION
**Pull request by antonio-elder**
This change is [Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)

### CODE REVIEW

**Review by rcameElder — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @antonio-elder)

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)* status: all files reviewed, 2 unresolved discussions (waiting on @antonio-elder)

___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 80 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Wh427gF8Ptheo3YR:-N_3Wh427gF8Ptheo3YS:b-6r6ts8) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L80)):*
> ```Kotlin
>             true -> {
>                 val snapshot = snapshottingSupport.findSnapshot(id)
>                 var newState : STATE? = null
> ```

if we know this will always be set, I think
```kotlin
lateinit newState: State?
```

Might be clearer.



_Code quote:_
```Kotlin
var newState : STATE? = null
```
___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 84 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Vsv_8Ica8ptbhdND:-N_3Vsv_8Ica8ptbhdNE:bl0u3d3) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L84)):*
> ```Kotlin
>         val data = Base64.getDecoder().decode(state)
>         val uncompressed = GZIPInputStream(data.inputStream()).use { it.readBytes() }
>         val state = mapper.readValue(uncompressed, clazz) as STATE
> ```

Nit: Rather than reading the uncompressed content out as a byte array, is it not possible to pass it directly to the object mapper?

I don't know for sure, but it could theoretically require less memory if it doesn't have to keep the whole json AND the deserialised object at the same time.



_Code quote:_
```Kotlin
        val uncompressed = GZIPInputStream(data.inputStream()).use { it.readBytes() }
        val state = mapper.readValue(uncompressed, clazz) as STATE
```

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 80 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Wh427gF8Ptheo3YR:-N_3YzDtCFzVV86VDdJr:bwcqd4v) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L80)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

if we know this will always be set, I think
```kotlin
lateinit newState: State?
```

Might be clearer.
</blockquote></details>

but isn't this a local variable? IntellIJ complains :sweat:

**Review by danieljelder — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @antonio-elder and @rcameElder)

___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 80 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Wh427gF8Ptheo3YR:-N_4AuFC0s-cXXhPOqkr:b-qtlzdy) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L80)):*
<details><summary><i>Previously, antonio-elder (Antonio Centeno Romero) wrote…</i></summary><blockquote>

but isn't this a local variable? IntellIJ complains :sweat: 
</blockquote></details>

ah, I thought `lateinit var` worked for local variables

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 80 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Wh427gF8Ptheo3YR:-N_4Bf_3CumIdBA1yXTs:bag4cnx) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L80)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Ah, looks like my comment was missing the `var`:

```kotlin
lateinit var newState: State
```
</blockquote></details>

Yes but still get the error

**Review by danieljelder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @rcameElder)

___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 80 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/40#-N_3Wh427gF8Ptheo3YR:-N_4Bo02Dorzcv12DiJj:bedbxmb) ([raw file](https://github.com/elder-oss/sourcerer/blob/809218a78ca6fcb18919249de9bee2648b0a38f3/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L80)):*
<details><summary><i>Previously, antonio-elder (Antonio Centeno Romero) wrote…</i></summary><blockquote>

Yes but still get the error 


</blockquote></details>

Oh, it sounds like STATE is `Any?` rather than `Any`. Not much we can do then I guess.

**Review by danieljelder — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @antonio-elder)

**Pull request merged**
