### PR TITLE
Snapshotting support

### PR DESCRIPTION
**Pull request by antonio-elder**
This change is [Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/37)

### CODE REVIEW

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 78 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAIWzG1kbcMKnLE3Lu:-NVAfhxABso7VHTbLu0T:ba3dfob) ([raw file](https://github.com/elder-oss/sourcerer/blob/007bea99c6e74368862e4cbf844a438e58fc0405/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L78)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

This is not a parameter here. It is on the next method though.
</blockquote></details>

Removed

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt` line 24 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAJ9ngBD50bGi4rj-B:-NVAfn5gAjgQ607ad20w:b-705ryl) ([raw file](https://github.com/elder-oss/sourcerer/blob/007bea99c6e74368862e4cbf844a438e58fc0405/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/EventStreams.kt#L24)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

This is a lot of parameters, and all but one are for snapshotting.

Maybe we can instead pass a snapshotting interface that takes all of these parameters, and the default implementation is a class that says never does anything with snapshots.

As it is now it's not clear that all the fields have to be non-null if snapshotting is enabled. We could of course add parameter validation in the constructor, but I think moving all these dependencies and logic to a delegate would be nicer.
</blockquote></details>

Moved to its own class

**Comment by antonio-elder** [comment]
*[`build.gradle` line 50 at r1](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAH6oP6Yc-0DRI8Quk:-NVAftVy2eQFRIkIFZt8:b-bw8e1h) ([raw file](https://github.com/elder-oss/sourcerer/blob/007bea99c6e74368862e4cbf844a438e58fc0405/build.gradle#L50)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

I don't think we want the local nexus in here. Maybe we could place it in our own gradle file instead
</blockquote></details>

Updated!

**Review by danieljelder — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/37)* status: all files reviewed, 4 unresolved discussions (waiting on @antonio-elder)

___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 20 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAoFu_BpEScls_m4G2:-NVAoFu_BpEScls_m4G3:b-fo2wze) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L20)):*
> ```Kotlin
> ) {
> 
>     fun <STATE> createNewSnapshotIfNecessary(
> ```

I'm guessing this should be the same `<STATE>` as what the whole class has?

If so, then I don't think you want `<STATE>` defined here, I believe that means it's been re-defined.



_Code quote:_
```Kotlin
<STATE>
```
___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 27 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAoaCI4n3VFhMHiSaD:-NVAoaCI4n3VFhMHiSaE:bgsy9ce) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L27)):*
> ```Kotlin
>     ) {
>         val minVersionsBetweenSnapshots = minVersionsBetweenSnapshots
>         val snapshottingVersion = snapshottingVersion
> ```

Unnecessary?



_Code quote:_
```Kotlin
        val minVersionsBetweenSnapshots = minVersionsBetweenSnapshots
        val snapshottingVersion = snapshottingVersion
```
___
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 29 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAomWA4FCDJejM5Z27:-NVAomWA4FCDJejM5Z28:burfru9) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L29)):*
> ```Kotlin
>         val snapshottingVersion = snapshottingVersion
>         val snapshotIsWellBehind = snapshot == null
>                 || (newVersion - snapshot.streamVersion) > minVersionsBetweenSnapshots
> ```

Does this mean we always create a snapshot on the first append? If so, we shouldn't need that right?



_Code quote:_
```Kotlin
        val snapshotIsWellBehind = snapshot == null
                || (newVersion - snapshot.streamVersion) > minVersionsBetweenSnapshots
```

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 27 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAoaCI4n3VFhMHiSaD:-NVAs7wfAYhZMM8N0pH9:b-rugzp) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L27)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Unnecessary?
</blockquote></details>

True. Removed

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 20 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAoFu_BpEScls_m4G2:-NVAsAxQ2-bOZPkVPBsC:ba3dfob) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L20)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

I'm guessing this should be the same `<STATE>` as what the whole class has?

If so, then I don't think you want `<STATE>` defined here, I believe that means it's been re-defined.
</blockquote></details>

Removed

**Comment by antonio-elder** [comment]
*[`sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt` line 29 at r2](https://reviewable.io/reviews/elder-oss/sourcerer/37#-NVAomWA4FCDJejM5Z27:-NVAsCS0-ZoYfe8ggd_K:b-kkl1dh) ([raw file](https://github.com/elder-oss/sourcerer/blob/573d502218fa407571c38921724406251bb8a9a9/sourcerer-kotlin/src/main/java/org/elder/sourcerer/kotlin/SnapshottingSupport.kt#L29)):*
<details><summary><i>Previously, danieljelder wrote…</i></summary><blockquote>

Does this mean we always create a snapshot on the first append? If so, we shouldn't need that right?
</blockquote></details>

True. I will default version to -1 so we only create the first one after the minimum number of versions has been reached

**Review by danieljelder — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/elder-oss/sourcerer/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @antonio-elder)

**Pull request merged**
